export interface ToolMeta {
  title: string;
  id: string; // slug/id referenced in legacy career history 'tools' arrays
  backgroundColor: string;
  textColor: string;
  icon: string; // URL or local path
}

export const tools: ToolMeta[] = [
  {
    title: "Figma",
    id: "figma",
    backgroundColor: "#9d56f7",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg",
  },
  {
    title: "Node",
    id: "node",
    backgroundColor: "#43853D",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg",
  },
  {
    title: "Express",
    id: "express",
    backgroundColor: "#000000",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg",
  },
  {
    title: "Postgres",
    id: "postgres",
    backgroundColor: "#336791",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg",
  },
  {
    title: "React",
    id: "react",
    backgroundColor: "#5ed3f3",
    textColor: "#000000",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
  },
  {
    title: "Typescript",
    id: "typescript",
    backgroundColor: "#007ACC",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg",
  },
  {
    title: "Redux",
    id: "redux",
    backgroundColor: "#764ABC",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/redux/redux-original.svg",
  },
  {
    title: "Material UI",
    id: "material-ui",
    backgroundColor: "#0081CB",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/materialui/materialui-original.svg",
  },
  {
    title: "Emotion CSS",
    id: "emotion-css",
    backgroundColor: "#D36AC2",
    textColor: "#FFFFFF",
    icon: "/assets/icons/emotion.png",
  },
  {
    title: "Playwright",
    id: "playwright",
    backgroundColor: "#1d8d22",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/playwright/playwright-original.svg",
  },
  {
    title: "Storybook",
    id: "storybook",
    backgroundColor: "#FF4785",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/storybook/storybook-original.svg",
  },
  {
    title: "Jest",
    id: "jest",
    backgroundColor: "#944058",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jest/jest-plain.svg",
  },
  {
    title: "Microvellum",
    id: "microvellum",
    backgroundColor: "#000",
    textColor: "#FFFFFF",
    icon: "/assets/icons/microvellum.png",
  },
  {
    title: "AutoCAD",
    id: "autocad",
    backgroundColor: "#AD343E",
    textColor: "#FFFFFF",
    icon: "/assets/icons/autocad.png",
  },
  {
    title: "Photoshop",
    id: "photoshop",
    backgroundColor: "#1D70A2",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/photoshop/photoshop-original.svg",
  },
  {
    title: "JavaScript",
    id: "javascript",
    backgroundColor: "#F7DF1E",
    textColor: "#000000",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg",
  },
  {
    title: "SASS",
    id: "sass",
    backgroundColor: "#CC6699",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg",
  },
  {
    title: "Next.js",
    id: "nextjs",
    backgroundColor: "#000000",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg",
  },
  {
    title: "CSS Modules",
    id: "css-modules",
    backgroundColor: "#264DE4",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg",
  },
  {
    title: "Firebase",
    id: "firebase",
    backgroundColor: "#FFCA28",
    textColor: "#000000",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebase/firebase-original.svg",
  },
  {
    title: "UI/UX",
    id: "ui-ux",
    backgroundColor: "#FF5733",
    textColor: "#FFFFFF",
    icon: "/assets/icons/ui-ux.png",
  },
  {
    title: "Tailwind",
    id: "tailwind",
    backgroundColor: "#06B6D4",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
  },
  {
    title: "GraphQL",
    id: "graphql",
    backgroundColor: "#E535AB",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/graphql/graphql-plain.svg",
  },
  {
    title: "HTML",
    id: "html",
    backgroundColor: "#E34F26",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg",
  },
  {
    title: "CSS",
    id: "css",
    backgroundColor: "#264DE4",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg",
  },
  {
    title: "Github",
    id: "github",
    backgroundColor: "#181717",
    textColor: "#FFFFFF",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg",
  },
  {
    title: "Inventor",
    id: "inventor",
    backgroundColor: "#dc8736",
    textColor: "#FFFFFF",
    icon: "/assets/icons/inventor.png",
  },
  {
    title: "Excel",
    id: "excel",
    backgroundColor: "#217346",
    textColor: "#FFFFFF",
    icon: "/assets/icons/excel.png",
  },
  {
    title: "MS Project",
    id: "project",
    backgroundColor: "#217346",
    textColor: "#FFFFFF",
    icon: "/assets/icons/project.png",
  },
];

export const toolLookup = Object.fromEntries(tools.map((t) => [t.id, t]));
